### ISSUE TITLE
README.md Cannot listen for callback

### ISSUE THREAD

**Issue by qinouz** [sebastianwachter/vue-scratchable#1]
@percentageUpdate="updatePoints"  
Change to @percentage-update="updatePoints" That's it

But the value calculated by the callback seems to be inaccurate. The value of the first callback is about 30%.

![image](https://user-images.githubusercontent.com/19344660/98194119-a07c8e80-1f59-11eb-8328-5dad2e82da2b.png)

**Comment by qinouz** [comment]
It has something to do with the picture. I changed a jpg picture and the calculation is accurate。。。

![image](https://user-images.githubusercontent.com/19344660/98196345-d96b3200-1f5e-11eb-901e-698046781d17.png)

**Comment by qinouz** [comment]
` const { context } = this.$scopedSlots.default()[0];`
`this.slotDomElement = context.$children.find((vnode) => vnode._uid === this._uid).$el;`

Why not use this.$el directly to get the outermost div

**Comment by sebastianwachter** [comment]
> @percentageUpdate="updatePoints"
> Change to @percentage-update="updatePoints" That's it
> 
> But the value calculated by the callback seems to be inaccurate. The value of the first callback is about 30%.
> 
> ![image](https://user-images.githubusercontent.com/19344660/98194119-a07c8e80-1f59-11eb-8328-5dad2e82da2b.png)

Can you provide me the image in question so I can reproduce this issue?

**Comment by sebastianwachter** [comment]
> ` const { context } = this.$scopedSlots.default()[0];`
> `this.slotDomElement = context.$children.find((vnode) => vnode._uid === this._uid).$el;`
> 
> Why not use this.$el directly to get the outermost div

I will give you a detailed explanation later. Too tired right now but it is good to do it that way 😄

**Comment by qinouz** [comment]
> > @percentageUpdate="updatePoints"
> > Change to @percentage-update="updatePoints" That's it
> > But the value calculated by the callback seems to be inaccurate. The value of the first callback is about 30%.
> > ![image](https://user-images.githubusercontent.com/19344660/98194119-a07c8e80-1f59-11eb-8328-5dad2e82da2b.png)
> 
> Can you provide me the image in question so I can reproduce this issue?
> 
> EDIT: Or better can you provide the vue file you are using in your example

I found the cause of the problem because my picture is a png type picture, and the transparent area may not be classified as a mask layer.

**Comment by sebastianwachter** [comment]
> > > @percentageUpdate="updatePoints"
> > > Change to @percentage-update="updatePoints" That's it
> > > But the value calculated by the callback seems to be inaccurate. The value of the first callback is about 30%.
> > > ![image](https://user-images.githubusercontent.com/19344660/98194119-a07c8e80-1f59-11eb-8328-5dad2e82da2b.png)
> > 
> > 
> > Can you provide me the image in question so I can reproduce this issue?
> > EDIT: Or better can you provide the vue file you are using in your example
> 
> I found the cause of the problem because my picture is a png type picture, and the transparent area may not be classified as a mask layer. When the picture is in jpg format, the calculation is fine

Yes that makes sense the calculation uses the alpha value of a certain pixel to determine whether it is scratched free or not. If the cover includes transparency the component doesn't require the user to scratch that certain area free since it is already scratched free in the sense that you can view what lies below.

Therefore the percentage value is that high. 30% of the area are already "free" (as in transparent).

**Comment by sebastianwachter** [comment]
> > ` const { context } = this.$scopedSlots.default()[0];`
> > `this.slotDomElement = context.$children.find((vnode) => vnode._uid === this._uid).$el;`
> > Why not use this.$el directly to get the outermost div
> 
> I will give you a detailed explanation later. Too tired right now but it is good to do it that way 😄

So: I actually can't give you a detailed explanation because there is none. I replaced it with `this.$el` in the version I just published. Also while looking into my code I found out that the `MutationObserver` was never working - I also fixed that in the latest version.
