### ISSUE TITLE
Clear scratchable layer programatically

### ISSUE THREAD

**Issue by ParkLai** [sebastianwachter/vue-scratchable#2]
As titled.

Use case:
When scratchable layer cleared percentage > N, clear all.

**Comment by sebastianwachter** [comment]
You'll need a `ref` to your scratchable like so:

```js
<vue-scratchable
  v-slot="{ init }"
  :brushOptions="brush"
  :hideOptions="hide"
  getPercentageCleared
  ref="scratchable"
  @percentage-update="updatePoints"
>
  ...
</vue-scratchable>
```

Then in the handler for the `percentage-update` event (in this case `updatePoints`) you can do something like this:

```js
updatePoints(percentage) {
  this.percentage = percentage;
  if (this.percentage >= 80) this.$refs.scratchable.clearArea();
},
```

So basically: Just call the `clearArea` function of your scratchable component when your condition is met.

**Comment by ParkLai** [comment]
It works! Might be helpful to others by adding this to the documentation.

Thank you!
